"""
HTML Generator Module
Generates professional HTML output using string templates
Supports all Aura commands with modern, responsive design
"""

from string import Template
from typing import List, Dict, Any
from datetime import datetime


class HTMLGenerator:
    """Generates HTML from parsed Aura commands"""

    # HTML Document Template
    HTML_TEMPLATE = Template("""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aura Generated Page</title>
    <style>
        $styles
    </style>
</head>
<body>
    <div class="container">
        $body_content
    </div>
    
    <script>
        $scripts
    </script>
    
    <!-- Generated by Aura Transpiler v1.0 on $timestamp -->
</body>
</html>""")

    # Theme CSS Templates
    THEMES = {
        'dark': """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            color: #eee;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
        }
        
        .container {
            background: rgba(255, 255, 255, 0.05);
            backdrop-filter: blur(10px);
            border-radius: 20px;
            padding: 40px;
            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
            border: 1px solid rgba(255, 255, 255, 0.1);
            max-width: 800px;
            width: 100%;
        }
        
        button {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            border: none;
            padding: 12px 30px;
            border-radius: 8px;
            font-size: 16px;
            cursor: pointer;
            transition: all 0.3s ease;
            margin: 10px 5px;
            box-shadow: 0 4px 15px rgba(102, 126, 234, 0.4);
        }
        
        button:hover {
            transform: translateY(-2px);
            box-shadow: 0 6px 20px rgba(102, 126, 234, 0.6);
        }
        
        input {
            background: rgba(255, 255, 255, 0.1);
            border: 1px solid rgba(255, 255, 255, 0.2);
            color: #eee;
            padding: 12px 20px;
            border-radius: 8px;
            font-size: 16px;
            margin: 10px 5px;
            width: calc(100% - 10px);
            transition: all 0.3s ease;
        }
        
        input::placeholder {
            color: rgba(255, 255, 255, 0.5);
        }
        
        input:focus {
            outline: none;
            border-color: #667eea;
            box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.2);
        }
        
        h1, h2, h3 {
            margin: 20px 0;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
        }
        
        p {
            line-height: 1.6;
            margin: 15px 0;
        }
        
        .card {
            background: rgba(255, 255, 255, 0.08);
            border-radius: 15px;
            padding: 25px;
            margin: 20px 0;
            border: 1px solid rgba(255, 255, 255, 0.1);
            transition: all 0.3s ease;
        }
        
        .card:hover {
            transform: translateY(-5px);
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);
        }
        
        .card h3 {
            margin-top: 0;
        }
        
        .card p {
            color: rgba(255, 255, 255, 0.8);
        }
        
        img {
            max-width: 100%;
            height: auto;
            border-radius: 10px;
            margin: 15px 0;
            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.3);
        }
        
        .center {
            text-align: center;
        }
        """,

        'light': """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
            color: #333;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
        }
        
        .container {
            background: white;
            border-radius: 20px;
            padding: 40px;
            box-shadow: 0 10px 40px rgba(0, 0, 0, 0.1);
            max-width: 800px;
            width: 100%;
        }
        
        button {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            border: none;
            padding: 12px 30px;
            border-radius: 8px;
            font-size: 16px;
            cursor: pointer;
            transition: all 0.3s ease;
            margin: 10px 5px;
            box-shadow: 0 4px 15px rgba(102, 126, 234, 0.3);
        }
        
        button:hover {
            transform: translateY(-2px);
            box-shadow: 0 6px 20px rgba(102, 126, 234, 0.5);
        }
        
        input {
            background: #f8f9fa;
            border: 2px solid #e9ecef;
            color: #333;
            padding: 12px 20px;
            border-radius: 8px;
            font-size: 16px;
            margin: 10px 5px;
            width: calc(100% - 10px);
            transition: all 0.3s ease;
        }
        
        input:focus {
            outline: none;
            border-color: #667eea;
            background: white;
        }
        
        h1, h2, h3 {
            margin: 20px 0;
            color: #2d3748;
        }
        
        p {
            line-height: 1.6;
            margin: 15px 0;
            color: #4a5568;
        }
        
        .card {
            background: #f8f9fa;
            border-radius: 15px;
            padding: 25px;
            margin: 20px 0;
            border: 2px solid #e9ecef;
            transition: all 0.3s ease;
        }
        
        .card:hover {
            transform: translateY(-5px);
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
            border-color: #667eea;
        }
        
        .card h3 {
            margin-top: 0;
            color: #2d3748;
        }
        
        .card p {
            color: #4a5568;
        }
        
        img {
            max-width: 100%;
            height: auto;
            border-radius: 10px;
            margin: 15px 0;
            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
        }
        
        .center {
            text-align: center;
        }
        """,

        'default': """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: #f0f0f0;
            padding: 20px;
        }
        
        .container {
            background: white;
            border-radius: 10px;
            padding: 30px;
            max-width: 800px;
            margin: 0 auto;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }
        
        button {
            background: #007bff;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            margin: 5px;
        }
        
        button:hover {
            background: #0056b3;
        }
        
        input {
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 5px;
            margin: 5px;
            width: calc(100% - 10px);
        }
        
        h1, h2, h3 {
            margin: 15px 0;
        }
        
        p {
            margin: 10px 0;
            line-height: 1.5;
        }
        
        .card {
            background: #f9f9f9;
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 20px;
            margin: 15px 0;
        }
        
        .card h3 {
            margin-top: 0;
        }
        
        img {
            max-width: 100%;
            height: auto;
            border-radius: 5px;
            margin: 10px 0;
        }
        
        .center {
            text-align: center;
        }
        """
    }

    def __init__(self):
        self.variables = {}
        self.theme = 'default'
        self.body_elements = []
        self.scripts = []
        self.last_element_id = None
        self.pending_actions = []

    def generate(self, commands: List) -> str:
        """
        Generate HTML from Aura commands

        Args:
            commands: List of AuraCommand objects

        Returns:
            Complete HTML string
        """
        # Reset state
        self.variables = {}
        self.theme = 'default'
        self.body_elements = []
        self.scripts = []
        self.last_element_id = None
        self.pending_actions = []

        # Process commands in order
        for cmd in commands:
            self._process_command(cmd)

        # Build final HTML
        return self._build_html()

    def _process_command(self, cmd):
        """Process a single command"""
        if cmd.command_type == 'variable':
            self._handle_variable(cmd)
        elif cmd.command_type == 'theme':
            self._handle_theme(cmd)
        elif cmd.command_type.startswith('ui_'):
            self._handle_ui_element(cmd)
        elif cmd.command_type == 'action_sequence':
            self._handle_action_sequence(cmd)
        elif cmd.command_type.startswith('action_'):
            self._handle_action(cmd)
        elif cmd.command_type.startswith('modifier_'):
            self._handle_modifier(cmd)
        elif cmd.command_type == 'layout_center':
            self._handle_layout_center(cmd)
        elif cmd.command_type == 'network_request':
            self._handle_network_request(cmd)
        elif cmd.command_type == 'deployment':
            self._handle_deployment(cmd)

    def _handle_variable(self, cmd):
        """Handle variable declaration"""
        obj = cmd.data['object']
        prop = cmd.data['property']
        value = cmd.data['value']

        if obj not in self.variables:
            self.variables[obj] = {}
        self.variables[obj][prop] = value

        # Add to scripts
        var_name = f"{obj}_{prop}".replace(' ', '_')
        self.scripts.append(f"const {var_name} = '{value}';")

    def _handle_theme(self, cmd):
        """Handle theme selection"""
        theme_name = cmd.data['theme'].lower()
        if theme_name in self.THEMES:
            self.theme = theme_name
        else:
            print(f"Warning: Unknown theme '{theme_name}', using default")
            self.theme = 'default'

    def _handle_ui_element(self, cmd):
        """Handle UI element creation"""
        element_type = cmd.command_type
        element_id = f"aura_elem_{len(self.body_elements)}"
        self.last_element_id = element_id

        if element_type == 'ui_button':
            text = cmd.data['text']
            html = f'<button id="{element_id}">{text}</button>'

        elif element_type == 'ui_heading':
            text = cmd.data['text']
            html = f'<h1 id="{element_id}">{text}</h1>'

        elif element_type == 'ui_paragraph':
            text = cmd.data['text']
            html = f'<p id="{element_id}">{text}</p>'

        elif element_type == 'ui_input':
            text = cmd.data['text']
            html = f'<input id="{element_id}" type="text" placeholder="{text}">'

        elif element_type == 'ui_card':
            title = cmd.data['title']
            description = cmd.data.get('description', '')
            html = f'''<div class="card" id="{element_id}">
                <h3>{title}</h3>
                {f'<p>{description}</p>' if description else ''}
            </div>'''

        elif element_type in ['ui_image', 'ui_image_simple']:
            url = cmd.data['url']
            alt = cmd.data.get('alt', 'Image')
            html = f'<img id="{element_id}" src="{url}" alt="{alt}">'

        else:
            html = f'<div id="{element_id}">Unknown element</div>'

        self.body_elements.append(html)

    def _handle_action(self, cmd):
        """Handle action/event binding"""
        if not self.last_element_id:
            print("Warning: Action defined without a preceding UI element")
            return

        event = cmd.data['event'].lower()
        element_id = self.last_element_id

        # Map event names to JavaScript events
        event_map = {
            'clicked': 'click',
            'click': 'click',
            'submit': 'submit',
            'hover': 'mouseenter',
        }
        js_event = event_map.get(event, 'click')

        # Generate action script based on type
        if cmd.command_type == 'action_display':
            content = cmd.data['content']
            action_code = f"alert('{content}');"

        elif cmd.command_type == 'action_alert':
            content = cmd.data['content']
            action_code = f"alert('{content}');"

        elif cmd.command_type == 'action_refresh':
            action_code = "location.reload();"

        else:
            action_code = "console.log('Action triggered');"

        # Store pending action to potentially combine with modifiers
        self.pending_actions.append(action_code)

        # Generate event listener
        all_actions = '\n            '.join(self.pending_actions)
        script = f"""
        document.getElementById('{element_id}').addEventListener('{js_event}', function() {{
            {all_actions}
        }});
        """
        self.scripts.append(script)

        # Clear pending actions after attaching
        self.pending_actions = []

    def _handle_action_sequence(self, cmd):
        """Handle sequential actions with 'then' keyword"""
        if not self.last_element_id:
            print("Warning: Action defined without a preceding UI element")
            return

        event = cmd.data['event'].lower()
        actions_string = cmd.data['actions']
        element_id = self.last_element_id

        # Map event names to JavaScript events
        event_map = {
            'clicked': 'click',
            'click': 'click',
            'submit': 'submit',
            'hover': 'mouseenter',
        }
        js_event = event_map.get(event, 'click')

        # Parse the action sequence inline (avoid circular import)
        import re
        action_parts = re.split(
            r',\s*then\s+', actions_string, flags=re.IGNORECASE)

        # Generate JavaScript code for each action
        action_codes = []
        for action_str in action_parts:
            action_str = action_str.strip()

            # Parse display/alert with quoted content
            display_match = re.match(
                r"(display|alert)\s+['\"]([^'\"]+)['\"]", action_str, re.IGNORECASE)
            if display_match:
                content = display_match.group(2)
                action_codes.append(f"alert('{content}');")
                continue

            # Parse refresh the page
            if re.match(r"refresh\s+the\s+page", action_str, re.IGNORECASE):
                action_codes.append("location.reload();")
                continue

            # Parse clear the input
            if re.match(r"clear\s+the\s+input", action_str, re.IGNORECASE):
                action_codes.append(
                    f"document.getElementById('{element_id}').value = '';")
                continue

            # Parse show/hide element
            show_match = re.match(
                r"(show|hide)\s+the\s+(\w+)", action_str, re.IGNORECASE)
            if show_match:
                action_type = show_match.group(1).lower()
                if action_type == 'hide':
                    action_codes.append(
                        f"document.getElementById('{element_id}').style.display = 'none';")
                else:
                    action_codes.append(
                        f"document.getElementById('{element_id}').style.display = 'block';")
                continue

            # Unknown action
            action_codes.append(
                f"console.log('Unknown action: {action_str}');")

        # Combine all actions into a single event handler
        all_actions = '\n            '.join(action_codes)
        script = f"""
        document.getElementById('{element_id}').addEventListener('{js_event}', function() {{
            {all_actions}
        }});
        """
        self.scripts.append(script)

    def _handle_modifier(self, cmd):
        """Handle action modifiers like 'And refresh the page'"""
        if cmd.command_type == 'modifier_refresh':
            # Add refresh to pending actions
            self.pending_actions.append("location.reload();")

            # If there's a last element, update its event listener
            if self.last_element_id and self.scripts:
                # Remove the last script and regenerate with the modifier
                self.scripts.pop()

                # Regenerate with all pending actions
                all_actions = '\n            '.join(self.pending_actions)
                script = f"""
        document.getElementById('{self.last_element_id}').addEventListener('click', function() {{
            {all_actions}
        }});
        """
                self.scripts.append(script)
                self.pending_actions = []

    def _handle_layout_center(self, cmd):
        """Handle layout centering"""
        # Add center class to the last element
        if self.body_elements:
            last_html = self.body_elements[-1]
            # Add center class
            if 'class="' in last_html:
                last_html = last_html.replace('class="', 'class="center ')
            else:
                last_html = last_html.replace('>', ' class="center">', 1)
            self.body_elements[-1] = last_html

    def _handle_network_request(self, cmd):
        """Handle network API requests"""
        url = cmd.data['url']
        data_type = cmd.data['data']

        # Generate fetch API call
        script = f"""
        // Fetch {data_type} from {url}
        fetch('https://{url}')
            .then(response => response.json())
            .then(data => {{
                console.log('{data_type}:', data);
                // You can process the {data_type} data here
            }})
            .catch(error => console.error('Error fetching {data_type}:', error));
        """
        self.scripts.append(script)

    def _handle_deployment(self, cmd):
        """Handle deployment command"""
        # Add a comment about deployment
        self.scripts.append("""
        // Deployment: This application is ready to go live!
        // To deploy, host the generated HTML file on any web server.
        console.log('Aura app ready for deployment!');
        """)

    def _build_html(self) -> str:
        """Build the final HTML document"""
        styles = self.THEMES.get(self.theme, self.THEMES['default'])
        body_content = '\n        '.join(
            self.body_elements) if self.body_elements else '<p>No content generated</p>'
        scripts = '\n        '.join(self.scripts)
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

        return self.HTML_TEMPLATE.substitute(
            styles=styles,
            body_content=body_content,
            scripts=scripts,
            timestamp=timestamp
        )
