"""
HTML Generator Module
Generates professional HTML output using string templates
"""

from string import Template
from typing import List, Dict, Any
from datetime import datetime


class HTMLGenerator:
    """Generates HTML from parsed Aura commands"""
    
    # HTML Document Template
    HTML_TEMPLATE = Template("""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aura Generated Page</title>
    <style>
        $styles
    </style>
</head>
<body>
    <div class="container">
        $body_content
    </div>
    
    <script>
        $scripts
    </script>
    
    <!-- Generated by Aura Transpiler v1.0 on $timestamp -->
</body>
</html>""")
    
    # Theme CSS Templates
    THEMES = {
        'dark': """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            color: #eee;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
        }
        
        .container {
            background: rgba(255, 255, 255, 0.05);
            backdrop-filter: blur(10px);
            border-radius: 20px;
            padding: 40px;
            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
            border: 1px solid rgba(255, 255, 255, 0.1);
            max-width: 800px;
            width: 100%;
        }
        
        button {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            border: none;
            padding: 12px 30px;
            border-radius: 8px;
            font-size: 16px;
            cursor: pointer;
            transition: all 0.3s ease;
            margin: 10px 5px;
            box-shadow: 0 4px 15px rgba(102, 126, 234, 0.4);
        }
        
        button:hover {
            transform: translateY(-2px);
            box-shadow: 0 6px 20px rgba(102, 126, 234, 0.6);
        }
        
        input {
            background: rgba(255, 255, 255, 0.1);
            border: 1px solid rgba(255, 255, 255, 0.2);
            color: #eee;
            padding: 12px 20px;
            border-radius: 8px;
            font-size: 16px;
            margin: 10px 5px;
            width: calc(100% - 10px);
            transition: all 0.3s ease;
        }
        
        input:focus {
            outline: none;
            border-color: #667eea;
            box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.2);
        }
        
        h1, h2, h3 {
            margin: 20px 0;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
        }
        
        p {
            line-height: 1.6;
            margin: 15px 0;
        }
        """,
        
        'light': """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
            color: #333;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
        }
        
        .container {
            background: white;
            border-radius: 20px;
            padding: 40px;
            box-shadow: 0 10px 40px rgba(0, 0, 0, 0.1);
            max-width: 800px;
            width: 100%;
        }
        
        button {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            border: none;
            padding: 12px 30px;
            border-radius: 8px;
            font-size: 16px;
            cursor: pointer;
            transition: all 0.3s ease;
            margin: 10px 5px;
            box-shadow: 0 4px 15px rgba(102, 126, 234, 0.3);
        }
        
        button:hover {
            transform: translateY(-2px);
            box-shadow: 0 6px 20px rgba(102, 126, 234, 0.5);
        }
        
        input {
            background: #f8f9fa;
            border: 2px solid #e9ecef;
            color: #333;
            padding: 12px 20px;
            border-radius: 8px;
            font-size: 16px;
            margin: 10px 5px;
            width: calc(100% - 10px);
            transition: all 0.3s ease;
        }
        
        input:focus {
            outline: none;
            border-color: #667eea;
            background: white;
        }
        
        h1, h2, h3 {
            margin: 20px 0;
            color: #2d3748;
        }
        
        p {
            line-height: 1.6;
            margin: 15px 0;
            color: #4a5568;
        }
        """,
        
        'default': """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: #f0f0f0;
            padding: 20px;
        }
        
        .container {
            background: white;
            border-radius: 10px;
            padding: 30px;
            max-width: 800px;
            margin: 0 auto;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }
        
        button {
            background: #007bff;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            margin: 5px;
        }
        
        button:hover {
            background: #0056b3;
        }
        
        input {
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 5px;
            margin: 5px;
            width: calc(100% - 10px);
        }
        
        h1, h2, h3 {
            margin: 15px 0;
        }
        
        p {
            margin: 10px 0;
            line-height: 1.5;
        }
        """
    }
    
    def __init__(self):
        self.variables = {}
        self.theme = 'default'
        self.body_elements = []
        self.scripts = []
    
    def generate(self, commands: List) -> str:
        """
        Generate HTML from Aura commands
        
        Args:
            commands: List of AuraCommand objects
            
        Returns:
            Complete HTML string
        """
        # Reset state
        self.variables = {}
        self.theme = 'default'
        self.body_elements = []
        self.scripts = []
        
        # Process commands in order
        for cmd in commands:
            self._process_command(cmd)
        
        # Build final HTML
        return self._build_html()
    
    def _process_command(self, cmd):
        """Process a single command"""
        if cmd.command_type == 'variable':
            self._handle_variable(cmd)
        elif cmd.command_type == 'theme':
            self._handle_theme(cmd)
        elif cmd.command_type == 'ui_element':
            self._handle_ui_element(cmd)
        elif cmd.command_type == 'action':
            self._handle_action(cmd)
    
    def _handle_variable(self, cmd):
        """Handle variable declaration"""
        obj = cmd.data['object']
        prop = cmd.data['property']
        value = cmd.data['value']
        
        if obj not in self.variables:
            self.variables[obj] = {}
        self.variables[obj][prop] = value
    
    def _handle_theme(self, cmd):
        """Handle theme selection"""
        theme_name = cmd.data['theme'].lower()
        if theme_name in self.THEMES:
            self.theme = theme_name
        else:
            print(f"Warning: Unknown theme '{theme_name}', using default")
            self.theme = 'default'
    
    def _handle_ui_element(self, cmd):
        """Handle UI element creation"""
        element = cmd.data['element'].lower()
        text = cmd.data['text']
        
        element_id = f"aura_{element}_{len(self.body_elements)}"
        
        html_map = {
            'button': f'<button id="{element_id}">{text}</button>',
            'input': f'<input id="{element_id}" type="text" placeholder="{text}">',
            'heading': f'<h1 id="{element_id}">{text}</h1>',
            'paragraph': f'<p id="{element_id}">{text}</p>',
            'div': f'<div id="{element_id}">{text}</div>',
            'span': f'<span id="{element_id}">{text}</span>',
        }
        
        if element in html_map:
            self.body_elements.append(html_map[element])
    
    def _handle_action(self, cmd):
        """Handle action/event binding"""
        event = cmd.data['event'].lower()
        action = cmd.data['action'].lower()
        content = cmd.data['content']
        
        # Find the last created element to attach the event
        if self.body_elements:
            last_element_id = self._extract_last_element_id()
            
            if last_element_id:
                script = self._generate_event_script(last_element_id, event, action, content)
                self.scripts.append(script)
    
    def _extract_last_element_id(self) -> str:
        """Extract the ID from the last created element"""
        if not self.body_elements:
            return None
        
        last_element = self.body_elements[-1]
        import re
        match = re.search(r'id="([^"]+)"', last_element)
        return match.group(1) if match else None
    
    def _generate_event_script(self, element_id: str, event: str, action: str, content: str) -> str:
        """Generate JavaScript for event handling"""
        event_map = {
            'clicked': 'click',
            'click': 'click',
            'submit': 'submit',
            'hover': 'mouseenter',
        }
        
        action_map = {
            'display': f"alert('{content}');",
            'show': f"alert('{content}');",
            'alert': f"alert('{content}');",
            'hide': f"document.getElementById('{element_id}').style.display = 'none';",
        }
        
        js_event = event_map.get(event, 'click')
        js_action = action_map.get(action, f"console.log('{content}');")
        
        return f"""
        document.getElementById('{element_id}').addEventListener('{js_event}', function() {{
            {js_action}
        }});
        """
    
    def _build_html(self) -> str:
        """Build the final HTML document"""
        styles = self.THEMES.get(self.theme, self.THEMES['default'])
        body_content = '\n        '.join(self.body_elements) if self.body_elements else '<p>No content generated</p>'
        scripts = '\n        '.join(self.scripts)
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        return self.HTML_TEMPLATE.substitute(
            styles=styles,
            body_content=body_content,
            scripts=scripts,
            timestamp=timestamp
        )
